<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ValueObjects\**" />
    <EmbeddedResource Remove="ValueObjects\**" />
    <None Remove="ValueObjects\**" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TechVeo.Notification.Application.Tests" />
    <InternalsVisibleTo Include="TechVeo.Notification.Domain.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TechVeo.Shared.Domain" Version="2.0.8-rc" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Exceptions.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Exceptions.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Exceptions.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Exceptions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
