//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechVeo.Notification.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechVeo.Notification.Application.Resources.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;div style=&apos;font-family:sans-serif;background-color:#0f1111;margin:0;padding:20px;color:#ffffff;&apos;&gt;&lt;div style=&apos;max-width:600px;margin:0 auto;background-color:#1a1d1e;border-radius:12px;overflow:hidden;border:1px solid #442222;&apos;&gt;&lt;div style=&apos;padding:30px;text-align:center;background-color:#121415;border-bottom:1px solid #333;&apos;&gt;&lt;span style=&apos;font-size:24px;font-weight:bold;color:#ffffff;&apos;&gt;🎥 TechVeo&lt;/span&gt;&lt;/div&gt;&lt;div style=&apos;padding:40px 30px;text-align:center;&apos;&gt;&lt;div style=&apos;display:inline-block;padding:6px 16px;ba [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;div style=&apos;font-family:sans-serif;background-color:#0f1111;margin:0;padding:20px;color:#ffffff;&apos;&gt;&lt;div style=&apos;max-width:600px;margin:0 auto;background-color:#1a1d1e;border-radius:12px;overflow:hidden;border:1px solid #333;&apos;&gt;&lt;div style=&apos;padding:30px;text-align:center;background-color:#121415;border-bottom:1px solid #333;&apos;&gt;&lt;span style=&apos;font-size:24px;font-weight:bold;color:#ffffff;&apos;&gt;🎥 TechVeo&lt;/span&gt;&lt;/div&gt;&lt;div style=&apos;padding:40px 30px;text-align:center;&apos;&gt;&lt;div style=&apos;display:inline-block;padding:6px 16px;backg [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
